export const baseObj = {
    name:'名称',
    checkAll:false,
    isIndeterminate:true,
    checks:[],
    child:[
      {
        name:'查看',
        prop:'read',
        value:false,
      },
      {
        name:'编辑',
        prop:'update',
        value:false,
      },
      {
        name:'删除',
        prop:'remove',
        value:false,
      },
      {
        name:'新增',
        prop:'create',
        value:false,
      } 
    ]
}
export const limit = [
  {
    label:'系统管理',
    rank:'father',
    children:[
      {
        label:'门店管理',
        rank:'mid',
      },
      {
        label:'部门管理',
        rank:'mid',
      },
      {
        label:'角色权限',
        rank:'mid',
      },
      {
        label:'员工管理',
        rank:'mid',
      },
      {
        label:'平台管理',
        rank:'mid',
        children:[
          {
            label:'会员卡等级设置',
            rank:'child'
          },
          {
            label:'会员卡积分设置',
            rank:'child'
          },
          {
            label:'会员充值设置',
            rank:'child'
          },
          {
            label:'自动回复配置',
            rank:'child'
          },
          {
            label:'保养提醒设置',
            rank:'child'
          },
          {
            label:'保险公司',
            rank:'child'
          },
          {
            label:'快捷回复设置',
            rank:'child'
          },
          {
            label:'消费类型',
            rank:'child'
          },
          {
            label:'关注后消息推送',
            rank:'child'
          },
        ]
      },
    ]
  },
  {
    label:'市场推广',
    rank:'father',
    children:[
      {
        label:'普通活动',
        rank:'mid',
      },
      {
        label:'推荐有礼',
        rank:'mid'
      },
      {
        label:'活动抽奖',
        rank:'mid'
      },
      {
        label:'摇一摇活动',
        rank:'mid'
      },
    ]
  },
  {
    label:'售后服务',
    rank:'father',
    children:[
      {
        label:'预约管理',
        rank:'mid',
        children:[
          {
            label:'预约时间设置',
            rank:'child',
          },
          {
            label:'预约管理',
            rank:'child',
          }
        ]
      },
      {
        label:'保险服务',
        rank:'mid'
      },
      {
        label:'救援服务',
        rank:'mid'
      },
      {
        label:'保养查询',
        rank:'mid'
      },
      {
        label:'养车知识',
        rank:'mid',
        children:[
          {
            label:'养车知识',
            rank:'child',
          },
          {
            label:'养车知识分类',
            rank:'child',
          }
        ]
      },
      {
        label:'车辆检测',
        rank:'mid',
        children:[
          {
            label:'检修记录',
            rank:'child',
          },
          {
            label:'检修项配置',
            rank:'child',
          },
          {
            label:'专项检测配置',
            rank:'child',
          }
        ]
      }
    ]
  },
  {
    label:'会员管理',
    rank:'father',
    children:[
      {
        label:'会员管理',
        rank:'mid',
      },
      {
        label:'车辆管理',
        rank:'mid'
      },
      {
        label:'积分管理',
        rank:'mid'
      },
      {
        label:'会员充值',
        rank:'mid'
      },
      {
        label:'充值明细',
        rank:'mid',
      },
      {
        label:'消费明细',
        rank:'mid',
      }
    ]
  },
  {
    label:'卡券管理',
    rank:'father',
    children:[
      {
        label:'奖品卡管理',
        rank:'mid',
      },
      {
        label:'抽奖模板管理',
        rank:'mid'
      },
      {
        label:'用户卡券管理',
        rank:'mid'
      },
      {
        label:'用户奖励',
        rank:'mid'
      },
      {
        label:'用户佣金提现',
        rank:'mid',
      },
      {
        label:'用户提现记录',
        rank:'mid',
      },
      {
        label:'员工奖励',
        rank:'mid',
      }
    ]
  },
  {
    label:'客服服务',
    rank:'father',
    children:[
      {
        label:'意见反馈',
        rank:'mid',
      },
      {
        label:'问卷调查',
        rank:'mid'
      },
    ]
  },
  {
    label:'统计分析',
    rank:'father',
    children:[
      {
        label:'售后',
        rank:'mid',
        children:[
          {
            label:'用户统计',
            rank:'child',
          },
          {
            label:'车辆统计',
            rank:'child',
          },
          {
            label:'业务统计',
            rank:'child',
          },
          {
            label:'活动统计',
            rank:'child',
          }
        ]
      },
      {
        label:'会员统计',
        rank:'mid'
      },
      {
        label:'提成日报',
        rank:'mid'
      },
      {
        label:'门店经营诊断',
        rank:'mid'
      }
    ]
  },
  {
    label:'企业中心',
    rank:'father',
    children:[
      {
        label:'消息中心',
        rank:'mid',
      },
      {
        label:'版本更新',
        rank:'mid'
      },
      {
        label:'共享中心',
        rank:'mid'
      },
      {
        label:'联系我们',
        rank:'mid'
      },
      {
        label:'门店风采',
        rank:'mid',
      }
    ]
  },
  {
    label:'用品商城',
    rank:'father',
    children:[
      {
        label:'汽车精品管理',
        rank:'mid',
      },
      {
        label:'精品订单管理',
        rank:'mid',
      },
      {
        label:'配件大类管理',
        rank:'mid',
      }
    ]
  },
  {
    label:'股东分红',
    rank:'father',
    children:[
      {
        label:'分红方案管理',
        rank:'mid',
      },
      {
        label:'股东信息管理',
        rank:'mid'
      },
      {
        label:'股东粉丝管理',
        rank:'mid'
      },
      {
        label:'股东分红汇总',
        rank:'mid'
      },
      {
        label:'股东分红明细',
        rank:'mid',
      },
      {
        label:'股东提现明细',
        rank:'mid',
      }
    ]
  },
  {
    label:'门店经营分析',
    rank:'father',
    children:[
      {
        label:'经营报表',
        rank:'mid',
      },
      {
        label:'会员报表',
        rank:'mid'
      },
      {
        label:'卡券报表',
        rank:'mid'
      },
      {
        label:'应收款报表',
        rank:'mid'
      },
      {
        label:'库存报表',
        rank:'mid',
      },
      {
        label:'股东报表',
        rank:'mid',
      }
    ]
  },
  {
    label:'员工分红',
    rank:'father',
    children:[
      {
        label:'员工分红设置',
        rank:'mid',
      },
      {
        label:'员工客户分配',
        rank:'mid'
      },
      {
        label:'惩罚设置',
        rank:'mid'
      },
      {
        label:'效果分析',
        rank:'mid'
      },
      {
        label:'员工贡献报表',
        rank:'mid',
      },
      {
        label:'员工分红汇总',
        rank:'mid',
      },
      {
        label:'员工提现明细',
        rank:'mid',
      },
      {
        label:'员工释放报表',
        rank:'mid'
      }
    ]
  },
  {
    label:'根目录',
    rank:'father',
    children:[
      {
        label:'主数据管理',
        rank:'mid',
        children:[
          {
            label:'供应商管理',
            rank:'child',
          },
          {
            label:'仓库管理',
            rank:'child',
          },
          {
            label:'商品分类管理',
            rank:'child',
          },
          {
            label:'商品管理',
            rank:'child',
          },
          {
            label:'项目分类管理',
            rank:'child',
          },
          {
            label:'项目管理',
            rank:'child',
          },
          {
            label:'物流公司管理',
            rank:'child',
          },
          {
            label:'支付方式管理',
            rank:'child',
          },
        ]
      },
      {
        label:'采购管理',
        rank:'mid',
        children:[
          {
            label:'采购订单',
            rank:'child',
          },
          {
            label:'采购入库',
            rank:'child',
          },
          {
            label:'采购退货',
            rank:'child',
          },
        ]
      },
      {
        label:'业务管理',
        rank:'mid',
        children:[
          {
            label:'业务开单',
            rank:'child',
          },
          {
            label:'业务出库',
            rank:'child',
          },
          {
            label:'业务退货',
            rank:'child',
          },
          {
            label:'业务结算',
            rank:'child',
          },
        ]
      },
      {
        label:'仓库管理',
        rank:'mid',
        children:[
          {
            label:'调拨发起',
            rank:'child',
          },
          {
            label:'调拨接收',
            rank:'child',
          },
        ]
      },
      {
        label:'盘点管理',
        rank:'mid',
        children:[
          {
            label:'日常盘点',
            rank:'child',
          }
        ]
      },
      {
        label:'套餐管理',
        rank:'mid',
        children:[
          {
            label:'套餐管理',
            rank:'child',
          },
          {
            label:'套餐销售',
            rank:'child',
          },
          {
            label:'会员套餐记录',
            rank:'child',
          },
        ]
      },
      {
        label:'付款管理',
        rank:'mid',
        children:[
          {
            label:'付款管理',
            rank:'child',
          }
        ]
      },
      {
        label:'挂账还款管理',
        rank:'mid',
        children:[
          {
            label:'挂账还款',
            rank:'child',
          }
        ]
      },
      {
        label:'报表管理',
        rank:'mid',
        children:[
          {
            label:'库存报表',
            rank:'child',
          },
          {
            label:'出入库明细表',
            rank:'child',
          },
          {
            label:'盘点明细表',
            rank:'child',
          },
          {
            label:'日报月报',
            rank:'child',
          },
          {
            label:'员工绩效汇总',
            rank:'child',
          },
          {
            label:'销售统计表',
            rank:'child',
          },
          {
            label:'采购明细表',
            rank:'child',
          },
          {
            label:'挂账单据明细表',
            rank:'child',
          },
          {
            label:'挂账还款明细表',
            rank:'child',
          },
          {
            label:'营业额统计表',
            rank:'child',
          },
          {
            label:'调拨接收',
            rank:'child',
          },
        ]
      },
    ]
  },
]