import {
  clearSearchForm ,
  handleSearchList,
  handleClearSearch,
} from './click'
const state = {
  search:{

  },
  types:[
    {
      name:'门店管理',
      params:['门店管理'],
      type:'',
      list:[
        {
          key:'门店名称',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'类型',
          type:'select',
          prop:'type',
          value:'',
          list:[
            {
              label:'集团',
              value:0
            },
            {
              label:'4S店',
              value:1
            },
            {
              label:'维修店',
              value:2
            }
          ],
        },
        {
          key:'服务开始日期',
          type:'date',
          prop:'start',
          value:'',
        },
        {
          key:'服务结束日期',
          type:'date',
          prop:'end',
          value:'',
        },
        {
          key:'状态',
          type:'select',
          prop:'state',
          value:'',
          list:[
            {
              label:'正常',
              value:1
            },
            {
              label:'禁用',
              value:0
            }
          ],
        }
      ]
    },
    {
      name:'staff',
      type:'',
      params:['员工管理','员工列表','关注用户列表'],
      list:[
        {
          key:'姓名',
          type:'input',
          prop:'realName',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'性别',
          type:'select',
          list:[
            {
              label:'男',
              value:1,
            },
            {
              label:'女',
              value:0,
            }
          ],
          prop:'sex',
          value:'',
        },
        {
          key:'微信昵称',
          type:'input',
          prop:'nickname',
          value:'',
        }
      ]
    },
    {
      name:'staffAdd',
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          prop:'',
          type:'input',
        },
        {
          key:'联系电话',
          value:'',
          prop:'',
          type:'input',
        },
        {
          key:'性别',
          value:'',
          prop:'',
          type:'select',
        }
      ]
    },
    {
      name:'保险公司',
      type:'',
      params:['保险公司'],
      list:[
        {
          key:'保险公司名称',
          type:'input',
          value:'',
          prop:'keyword',
        }
      ]
    },
    {
      name:'快捷回复设置',
      type:'',
      params:['快捷回复设置'],
      list:[
        {
          key:'使用角色类型',
          type:'select',
          value:'',
          prop:'roleId',
          list:[
            {
              label:'销售顾问',
              value:0
            },
            {
              label:'续保顾问',
              value:1
            },
            {
              label:'售后顾问',
              value:3
            }
          ]
        }
      ]
    },
    {
      name:'汽车精品管理',
      type:'',
      params:['汽车精品管理'],
      list:[
        {
          key:'配件名称',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'请选择精品大类',
          type:'select',
          prop:'categoryId',
          value:'',
          list:[],
        },
        {
          key:'是否推荐',
          type:'select',
          prop:'recommend',
          value:'',
          list:[
            {
              label:'是',
              value:1
            },
            {
              label:'否',
              value:0
            }
          ],
        },
        {
          key:'积分兑换',
          type:'select',
          prop:'supportIntegralChange',
          value:'',
          list:[
            {
              label:'是',
              value:1,
            },
            {
              label:'否',
              value:0
            }
          ]
        },
        {
          key:'是否直降',
          type:'select',
          prop:'whetherDrop',
          value:'',
          list:[
            {
              label:'是',
              value:1
            },
            {
              label:'否',
              value:0
            }
          ]
        }
      ]
    },
    {
      name:'精品订单管理',
      params:['精品订单管理'],
      type:'',
      list:[
        {
          key:'订单编号',
          type:'input',
          prop:'orderNum',
          value:'',
        },
        {
          key:'姓名',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'telephone',
          value:'',
        },
        {
          key:'配件名称',
          type:'input',
          prop:'commodityName',
          value:'',
        },
        {
          key:'状态',
          type:'select',
          prop:'state',
          value:'',
          list:[
            {
              label:'未支付',
              value:'0'
            },
            {
              label:'已支付',
              value:1
            },
            {
              label:'已提货',
              value:2
            }
          ],
        },
        {
          key:'订单开始日期',
          type:'date',
          value:'',
          prop:'orderDate',
        },
        {
          key:'订单结束日期',
          type:'date',
          value:'',
          prop:'orderEnd',
        },
        {
          key:'提货开始日期',
          type:'date',
          value:'',
          prop:'deliveryDate',
        },
        {
          key:'提货结束日期',
          type:'date',
          value:'',
          prop:'deliveryEnd',
        }
      ]
    },
    {
      name:'精品订单详情',
      params:['精品订单详情'],
      type:'',
      list:[
        {
          key:'订单编号',
          type:'input',
          prop:'orderNum',
          value:'',
        },
        {
          key:'姓名',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'telephone',
          value:'',
        },
        {
          key:'状态',
          type:'select',
          prop:'state',
          value:'',
          list:[
            {
              label:'未支付',
              value:'0'
            },
            {
              label:'已支付',
              value:1
            },
            {
              label:'已提货',
              value:2
            }
          ],
        },
        {
          key:'订单开始日期',
          type:'date',
          value:'',
          prop:'orderDate',
        },
        {
          key:'订单结束日期',
          type:'date',
          value:'',
          prop:'orderEnd',
        },
        {
          key:'提货开始日期',
          type:'date',
          value:'',
          prop:'deliveryDate',
        },
        {
          key:'提货结束日期',
          type:'date',
          value:'',
          prop:'deliveryEnd',
        }
      ]
    },
    {
      name:'配件大类管理',
      params:['配件大类管理'],
      type:'',
      list:[
        {
          key:'精品大类名称',
          type:'input',
          value:'',
          prop:'category',
        }
      ]
    },
    {
      name:'会员列表',
      type:'',
      params:['会员列表', '昨日新增会员', '本月会员累计'],
      list:[
        {
          key:'姓名',
          type:'input',
          prop:'realName',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'会员等级',
          type:'select',
          prop:'grade',
          value:'',
          list:[
            {
              label:'普通会员1',
              value:1
            }
          ],
        },
        {
          key:'性别',
          type:'select',
          prop:'sex',
          value:'',
          list:[
            {
              label:'男',
              value:'男',
            },
            {
              label:'女',
              value:'女',
            }
          ],
        },
        // {
        //   key:'顾问类型',
        //   type:'select',
        //   prop:'state',
        //   value:'',
        //   list:[
        //     {
        //       label:'保养顾问',
        //       value:1,
        //     },
        //     {
        //       label:'保险顾问',
        //       value:2,
        //     },
        //     {
        //       label:'续保顾问',
        //       value:3
        //     }
        //   ]
        // },
        {
          key:'保养顾问',
          type:'select',
          prop:'upkeepEmployee',
          value:'',
          list:[]
        },
        {
          key:'保险顾问',
          type:'select',
          prop:'safeEmployee',
          value:'',
          list:[]
        },
        {
          key:'续保顾问',
          type:'select',
          prop:'renewEmployee',
          value:'',
          list:[]
        },
        {
          key:'状态',
          type:'select',
          prop:'attentionState',
          value:'',
          list:[
            {
              label:'已关注',
              value:1,
            },
            {
              label:'未关注',
              value:'0'
            }
          ],
        },
        {
          key:'推荐人',
          type:'input',
          prop:'userName',
          value:'',
        },
        {
          key:'车牌号',
          type:'input',
          prop:'plateNum',
          value:'',
        },
        {
          key:'车型',
          type:'input',
          prop:'carModel',
          value:'',
        },
        {
          key:'关注开始日期',
          type:'date',
          prop:'startCreateTime',
          value:'',
        },
        {
          key:'关注结束日期',
          type:'date',
          prop:'endCreateTime',
          value:'',
        },
        {
          key:'积分区间(最小值)',
          type:'input',
          prop:'minIntegral',
          value:'',
        },
        {
          key:'积分区间(最大值)',
          type:'input',
          prop:'maxIntegral',
          value:'',
        },
      ]
    }, 
    {
      name:'会员充值',
      type:'',
      params:['会员充值'],
      list:[
        {
          key:'会员姓名',
          type:'input',
          prop:'realName',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'车牌号',
          type:'input',
          prop:'plateNum',
          value:'',
        },
      ]
    },
    {
      name:'车辆管理',
      type:'',
      params:['车辆管理'],
      list:[
        {
          key:'姓名',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'telephone',
          value:'',
        },
        {
          key:'上次保养开始日期',
          type:'date',
          prop:'startLastMaintainTime',
          value:'',
        },
        {
          key:'上次保养结束日期',
          type:'date',
          prop:'endLastMaintainTime',
          value:'',
        },
        {
          key:'保养到期',
          type:'select',
          prop:'maintainState',
          value:'',
          list:[
            {
              label:'已到期',
              value:1
            },
            {
              label:'未到期',
              value:'0'
            }
          ]
        },
        {
          key:'保险购买开始日期',
          type:'date',
          prop:'StartInsuranceStart',
          value:'',
        },
        {
          key:'保险购买结束日期',
          type:'date',
          prop:'endInsuranceStart',
          value:'',
        },
        {
          key:'保险到期',
          type:'select',
          prop:'insuranceState',
          value:'',
          list:[
            {
              label:'已到期',
              value:1,
            },
            {
              label:'未到期',
              value:'0'
            }
          ]
        },
        {
          key:'车型',
          type:'input',
          prop:'carModel',
          value:'',
        },
        {
          key:'车牌号',
          type:'input',
          prop:'plateNum',
          value:'',
        }
      ]
    },
    {
      name:'发布抽奖模板',
      params:['编辑抽奖模板'],
      type:'',
      list:[
        {
          key:'模板名称',
          type:'input',
          prop:'',
          value:'',
        },
        {
          key:'简介',
          type:'input',
          prop:'',
          value:'',
        }
      ]
    },
    {
      name:'用户佣金提现',
      params:['用户佣金提现'],
      type:'',
      list:[
        {
          key:'姓名',
          type:'input',
          prop:'realName',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'车牌号',
          type:'input',
          prop:'carNumber',
          value:'',
        }
      ],
    },
    {
      name:'积分管理',
      params:['积分管理'],
      type:'',
      list:[
        {
          key:'会员姓名',
          type:'input',
          prop:'realName',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'微信昵称',
          type:'input',
          prop:'nickName',
          value:'',
        },
        {
          key:'积分发生开始日期',
          type:'date',
          prop:'startOperationTime',
          value:'',
        },
        {
          key:'积分发生结束日期',
          type:'date',
          prop:'endOperationTime',
          value:'',
        },
        {
          key:'会员等级',
          type:'select',
          prop:'memberId',
          value:'',
        },
        {
          key:'积分改变类型',
          type:'select',
          prop:'type',
          value:'',
          list:[
            {
              label:'增加',
              value:1,
            },
            {
              label:'减少',
              value:'0'
            }
          ]
        },
        {
          key:'业务类型',
          type:'select',
          prop:'businessType',
          value:'',
        },
      ]
    },  
    {
      name:'充值明细',
      params:['充值明细'],
      type:'',
      list:[
        {
          key:'订单号',
          type:'input',
          prop:'orderNum',
          value:'',
        },
        {
          key:'会员姓名',
          type:'input',
          prop:'realName',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'操作人',
          type:'input',
          prop:'employeeName',
          value:'',
        },
        {
          key:'充值方式',
          type:'select',
          prop:'rechargeType',
          value:'',
          list:[],
        },
        {
          key:'开始日期',
          type:'date',
          prop:'startCreateTime',
          value:'',
        },
        {
          key:'结束日期',
          type:'date',
          prop:'endCreateTime',
          value:'',
        },
      ]
    }, 
    {
      name:'操作日志',
      params:['操作日志'],
      type:'',
      list:[
        {
          key:'日志号',
          type:'input',
          prop:'id',
          value:'',
        },
        {
          key:'用户名称',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key: '模块名称',
          type: 'select',
          prop: 'moduleName',
          list:[
            {
              label: '系统管理',
              value: 0
            },
            {
              label: '会员管理',
              value: 1,
            },
            {
              label: '卡券管理',
              value: 2,
            },
            {
              label: '用品管理',
              value: 3
            }
          ]
        },
        {
          key:'开始日期',
          type:'date',
          prop:'startTime',
          value:'',
        },
        {
          key:'结束日期',
          type:'date',
          prop:'endTime',
          value:'',
        },
      ]
    },
    {
      name:'消息中心',
      params:['消息中心'],
      type:'',
      list:[
        {
          key:'消息类型',
          type:'select',
          prop:'orderNum',
          value:'',
          list:[
            {
              label:'公告',
              value:1,
            },
            {
              label:'提醒',
              value:2,
            }
          ]
        },
        {
          key:'开始日期',
          type:'date',
          prop:'startCreateTime',
          value:'',
        },
        {
          key:'结束日期',
          type:'date',
          prop:'endCreateTime',
          value:'',
        },
      ]
    },
    {
      name:'消费明细',
      params:['消费明细'],
      type:'',
      list:[
        {
          key:'会员姓名',
          type:'input',
          prop:'realName',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'车牌号',
          type:'input',
          prop:'plateNum',
          value:'',
        },
        {
          key:'选择消费项目',
          type:'select',
          prop:'mealName',
          value:'',
          list:[
            {
              label:'一般维修',
              value:'一般维修',
            },
            {
              label:'购买保险',
              value:'购买保险',
            },
            {
              label:'美容洗车',
              value:'美容洗车',
            },
            {
              label:'汽车精品',
              value:'汽车精品',
            },
            {
              label:'套餐销售',
              value:'套餐销售',
            },
            {
              label:'其他',
              value:'其他',
            },
          ]
          
        },
        {
          key:'会员卡扣除状态',
          type:'select',
          prop:'status',
          value:'',
          list:[
            {
              label:'已扣除',
              value:1
            },
            {
              label:'未扣除',
              value:0,
            }
          ],
        },
        {
          key:'开始日期',
          type:'date',
          prop:'startTime',
          value:''
        },
        {
          key:'结束日期',
          type:'date',
          prop:'endTime',
          value:'',
        },
      ]
    },
    {
      name:'奖品卡券管理',
      params:['奖品卡券管理'],
      type:'',
      list:[
        {
          key:'卡券名称',
          type:'input',
          prop:'couponName',
          value:'',
        },
        {
          key:'奖品卡券类型',
          type:'select',
          prop:'couponType',
          value:'',
          list:[
            {
              label:'实物奖品',
              value:'0'
            },
            {
              label:'电子代金券',
              value:'1'
            }
          ],
        },
        {
          key:'有效日期',
          type:'input',
          prop:'validDays',
          value:'',
        }
      ]
    },
    {
      name:'抽奖模板设置',
      params:['抽奖模板设置'],
      type:'',
      list:[
        {
          key:'模板名称',
          type:'input',
          prop:'name',
          default:'',
        }
      ]
    },
    {
      name:'用户卡券管理',
      params:['用户卡券管理','查看领取明细'],
      type:'',
      list:[
        {
          key:'姓名',
          prop:'realName',
          type:'input',
          value:''
        },
        {
          key:'联系电话',
          prop:'phone',
          type:'input',
          value:''
        },
        {
          key:'卡券名称',
          prop:'couponName',
          type:'input',
          value:''
        },
        {
          key:'卡券编号',
          prop:'codeNum',
          type:'input',
          value:''
        },
        {
          key:'类型',
          prop:'couponType',
          type:'select',
          value:'',
          list:[
            {
              label:'实物奖品',
              value:0
            },
            {
              label:'电子代金券',
              value:1
            }
          ]
        },
        {
          key:'获取开始日期',
          prop:'StartDate',
          type:'date',
          value:''
        },
        {
          key:'获取结束日期',
          prop:'EndDate',
          type:'date',
          value:''
        },
        {
          key:'状态',
          prop:'state',
          type:'select',
          value:'',
          list:[
            {
              label:'未使用',
              value:'0'
            },
            {
              label: '已使用',
              value:1
            },
            {
              label:'已过期',
              value:2
            }
          ]
        },
        {
          key:'卡券来源',
          prop:'reserved1',
          type:'select',
          value:'',
          list:[]
        },
      ]
    },
    {
      name:'用户卡券发放',
      params:['用户卡券发放'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'车型',
          value:'',
          type:'default',
          prop:'carModel',
        },
        {
          key:'车牌',
          value:'',
          type:'default',
          prop:'carNum',
        },
        {
          key:'性别',
          value:'',
          type:'select',
          prop:'sex',
          list:[
            {
              label:'男',
              value:1
            },
            {
              label:'女',
              value:'0'
            }
          ],
        },
        {
          key:'会员等级',
          value:'',
          type:'select',
          prop:'memberId',
          list:[],
        },
        {
          key:'销售顾问',
          value:'',
          type:'select',
          prop:'saleEmployeeName',
          list:[],
        },
        {
          key:'保养顾问',
          value:'',
          type:'select',
          prop:'upKeepEmployeeName',
          list:[],
        },
        {
          key:'保险顾问',
          value:'',
          type:'select',
          prop:'safeEmployeeName',
          list:[],
        },
        {
          key:'续保顾问',
          value:'',
          type:'select',
          prop:'renewEmplyoeeName',
          list:[],
        },
        {
          key:'个人信息是否完善',
          value:'',
          type:'select',
          prop:'personlInfo',
          list:[
            {
              label:'已完善',
              value:1
            },
            {
              label:'未完善',
              value:'0'
            }
          ],
        },
        {
          key:'车辆信息是否完善',
          value:'',
          type:'select',
          prop:'carInfo',
          list:[
            {
              label:'已完善',
              value:1
            },
            {
              label:'未完善',
              value:'0'
            }
          ],
        },
      ]
    },
    {
      name:'用户提现',
      params:['用户提现记录'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'realName',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'车牌号',
          value:'',
          type:'default',
          prop:'carNumber',
        },
        {
          key:'提现开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'提现结束日期',
          value:'',
          type:'date',
          prop:'endDate',
        }
      ],
    },
    {
      name:'用户奖励',
      params:['用户奖励'],
      type:'',
      list:[
        {
          key:'用户姓名',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'奖励类型',
          value:'',
          type:'select',
          prop:'awardType',
          list:[
            {
              label: '消费',
              value: 1
            },
            {
              label: '分享',
              value:'0'
            }
          ]
        },
        {
          key:'活动卡券',
          value:'',
          type:'select',
          prop:'couponName',
        },
        {
          key:'消费最小金额',
          value:'',
          type:'input',
          prop:'minMoney',
        },
        {
          key:'消费最大金额',
          value:'',
          type:'input',
          prop:'maxMoney',
        },
        {
          key:'返利开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'返利结束日期',
          value:'',
          type:'date',
          prop:'',
        },
        {
          key:'奖励金额',
          value:'',
          type:'input',
          prop:'awardMoney',
        }
      ]
    },
    {
      name:'员工奖励',
      params:['员工奖励'],
      type:'',
      list:[
        {
          key:'员工姓名',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'消费最小金额',
          value:'',
          type:'input',
          prop:'minMoney',
        },
        {
          key:'消费最大金额',
          value:'',
          type:'input',
          prop:'maxMoney',
        },
        {
          key:'奖励开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'奖励结束日期',
          value:'',
          type:'date',
          prop:'endDate',
        },
        {
          key:'活动卡券',
          value:'',
          type:'select',
          prop:'activityCard',
        },
        {
          key:'发放状态',
          value:'',
          type:'select',
          prop:'status',
          list:[
            {
              label:'已发放',
              value:1
            },
            {
              label:'未发放',
              value:'0'
            }
          ]
        },
        {
          key:'奖励类型',
          value:'',
          type:'select',
          prop:'rewardType',
          list:[
            {
              label:'分享',
              value:1
            },
            {
              label:'消费',
              value:'0'
            }
          ]
        }
      ]
    },
    {
      name:'待办事项',
      params:['待办事项'],
      type:'',
      list:[
        {
          key:'带单审核单号',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'发起人',
          value:'',
          type:'default',
          prop:'phone',
        },
      ]
    },
    {
      name:'系统消息',
      params:['系统消息'],
      type:'',
      list:[
        {
          key:'消息类型',
          value:'',
          type:'select',
          prop:'type',
          list:[
            {
              label:'公告',
              value:0
            },
            {
              label:'提醒',
              value:1
            }
          ]
        },
        {
          key:'发布开始时间',
          value:'',
          type:'date',
          prop:'startTime',
        },
        {
          key:'发布结束时间',
          value:'',
          type:'endTime',
          prop:''
        }
      ]
    },
    {
      name:'已办事项',
      params:['已办事项'],
      type:'',
      list:[
        {
          key:'待办审核单号',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'流程状态',
          value:'',
          type:'select',
          prop:'phone',
          list:[
            {
              label:'已拒绝',
              value:0
            },
            {
              label:'已通过',
              value:1
            }
          ]
        },
        {
          key:'审核人',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'发起人',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'办理日期',
          value:'',
          type:'date',
          prop:'phone',
        },
      ]
    },
    {
      name:'普通活动',
      params:['普通活动','活动抽奖'],
      type:'',
      list:[
        {
          key:'活动标题',
          value:'',
          type:'default',
          prop:'activitieName',
        },
        {
          key:'活动开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'活动结束日期',
          value:'',
          type:'date',
          prop:'endDate',
        },
        {
          key:'发布开始日期',
          value:'',
          type:'date',
          prop:'publishStartDate',
        },
        {
          key:'发布结束日期',
          value:'',
          type:'date',
          prop:'getPublishEndDate',
        },
        {
          key:'活动栏目',
          value:'',
          type:'select',
          prop:'column',
        },
        {
          key:'活动类型',
          value:'',
          type:'select',
          prop:'state',
          list:[
            {
              label:'未开始',
              value:0
            },
            {
              label:'进行中',
              value:1
            },
            {
              label:'已结束',
              value:2
            },
            {
              label:'已关闭',
              value:3
            },
          ]
        },
      ],
    },
    {
      name:'活动中奖',
      params:['活动中奖'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'电话',
          value:'',
          type:'input',
          prop:'phone',
        },
      ],
    },
    {
      name:'精准获客',
      params:['精准获客'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'联系电话',
          value:'',
          type:'input',
          prop:'phone',
        },
        {
          key:'是否精准客户',
          value:'',
          type:'select',
          prop:'accurateCustomers',
          list:[
            {
              label:'是',
              value:1
            },
            {
              label:'否',
              value:0
            }
          ]
        },
        {
          key:'是否转发',
          value:'',
          type:'select',
          prop:'whetherForwarding',
          list:[
            {
              label:'是',
              value:1
            },
            {
              label:'否',
              value:0
            }
          ]
        },
        {
          key:'活动开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'活动结束日期',
          value:'',
          type:'date',
          prop:'endDate',
        },
      ],
    },
    {
      name:'报名查询',
      params:['报名查询'],
      type:'',
      list:[
        {
          key:'参与人姓名',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'参与人联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'推荐人姓名',
          value:'',
          type:'default',
          prop:'refereer',
        },
        {
          key:'推荐人联系电话',
          value:'',
          type:'default',
          prop:'refereeerPhone',
        },
        {
          key:'活动开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'活动结束日期',
          value:'',
          type:'date',
          prop:'endDate',
        },
        {
          key:'报名状态',
          value:'',
          type:'select',
          prop:'status',
          list:[
            {
              label:'已确认',
              value:1
            },
            {
              label:'未确认',
              value:0
            },
            {
              label:'已领取',
              value:2
            }
          ],
        },
        {
          key:'支付状态',
          value:'',
          type:'select',
          prop:'isValid',
          list:[
            {
              label:'未支付',
              value:0
            },
            {
              label:'已支付',
              value:1
            }
          ]
        },
      ],
    },
    {
      name:'推荐有礼',
      params:['推荐有礼'],
      type:'',
      list:[
        {
          key:'推荐人手机号',
          value:'',
          type:'default',
          prop:'referrerPhone',
        },
        {
          key:'被推荐人手机号',
          value:'',
          type:'default',
          prop:'userPhone',
        },
        {
          key:'推荐类型',
          value:'',
          type:'select',
          prop:'type',
          list:[
            {
              label: '保险',
              value: 0
            },
            {
              label: '保养维护',
              value: 1
            }
          ]
        },
        {
          key:'推荐状态',
          value:'',
          type:'select',
          prop:'currentState',
          list:[
            {
              label: '待确认',
              value: 0
            },
            {
              label: '已确认',
              value: 1
            },
            {
              label: '已领取',
              value: 2
            },
            {
              label: '已失效',
              value: 3
            }
          ]
        },
        {
          key:'推荐开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'推荐结束日期',
          value:'',
          type:'date',
          prop:'endDate',
        },
      ],
    },
    {
      name:'摇一摇活动',
      params:['摇一摇活动'],
      type:'',
      list:[
        {
          key:'场次名称',
          value:'',
          type:'default',
          prop:'fieldName',
        },
        {
          key:'发布开始日期',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'发布结束日期',
          value:'',
          type:'date',
          prop:'endDate',
        },
        {
          key:'活动状态',
          value:'',
          type:'select',
          prop:'activeState',
          list:[
            {
              label: '进行中',
              value: 1
            },
            {
              label: '已结束',
              value: 0
            }
          ]
        }
      ],
    },
    {
      name:'摇一摇活动中奖查询',
      params:['摇一摇中奖'],
      type:'',
      list:[
        {
          key:'参与人姓名',
          value:'',
          type:'default',
          prop:'name'
        },
        {
          key:'参与人联系电话',
          value:'',
          type:'default',
          prop: 'phone'
        },
      ],
    },
    {
      name:'预约管理',
      params:['预约管理'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'预约类型',
          value:'',
          type:'select',
          prop:'bookingSetId',
          list:[
            {
              label:'爱车保养',
              value:1
            },
            {
              label:'事故维修',
              value:2
            },
            {
              label:'故障检查',
              value:3
            },
            {
              label:'购买保险',
              value:4
            },
            {
              label:'爱车美容',
              value:5
            },
            {
              label:'其他',
              value:6
            },
          ],
        },
        {
          key:'预约状态',
          value:'',
          type:'select',
          prop:'state',
          list:[
            {
              label:'未确认',
              value:0
            },
            {
              label:'未到店',
              value:1
            },
            {
              label:'已确认',
              value:2
            },
            {
              label:'已取消',
              value:3
            },
          ],
        },
        {
          key:'预约开始时间',
          value:'',
          type:'date',
          prop:'orderTimeStart',
        },
        {
          key:'预约结束时间',
          value:'',
          type:'date',
          prop:'orderTimeEnd',
        },
      ]
    },
    {
      name:'保险服务',
      params:['保险服务'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'userName',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'状态',
          value:'',
          type:'select',
          prop:'state',
          list:[
            {
              label:'未确认',
              value:0
            },
            {
              label:'已确认',
              value:1
            }
          ]
        },
      ]
    },
    {
      name:'检修记录',
      params:['检修记录'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'userName',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'车牌',
          value:'',
          type:'default',
          prop:'plateNum',
        },
        {
          key:'检测开始时间',
          value:'',
          type:'date',
          prop:'detectionTimeStart',
        },
        {
          key:'检测结束时间',
          type:'date',
          value:'',
          prop:'detectionTimeEnd',
        }
      ]
    },
    {
      name:'救援服务',
      params:['救援服务'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'userName'
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone'
        },
      ]
    },
    {
      name:'养车知识',
      params:['养车知识'],
      type:'',
      list:[
        {
          key:'文章标题',
          value:'',
          type:'default',
          prop:'title'
        },
        {
          key:'文章类别',
          value:'',
          type:'select',
          prop:'typeId'
        }
      ]
    },
    {
      name:'业务开单',
      params:['业务开单'],
      type:'',
      list:[
        {
          key:'业务单号',
          value:'',
          type:'default',
          prop:'orderCode'
        },
        {
          key:'会员名称',
          value:'',
          type:'default',
          prop:'realName',
        },
        {
          key:'会员电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'车牌号',
          value:'',
          type:'default',
          prop:'plateNum',
        },
        {
          key:'开始时间',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'结束时间',
          value:'',
          type:'date',
          prop:'endDate',
        },
      ]
    },
    {
      name:'意见反馈',
      params:['意见反馈'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
          prop:'userName',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'反馈开始时间',
          value:'',
          prop:'startFeedbackTime',
          type:'date',
        },
        {
          key:'反馈结束时间',
          value:'',
          type:'date',
          prop:'endFeedbackTime',
        },
        {
          key:'回复状态',
          value:'',
          type:'select',
          prop:'processingState',
          list:[
            {
              label:'未回复',
              value:0
            },
            {
              label:'已回复',
              value:1
            }
          ]
        },
        {
          key:'反馈类型',
          value:'',
          type:'select',
          prop:'feedbackType',
          list:[
            {
              label:'保险',
              value:0,
            },
            {
              label:'续保',
              value:1,
            },
            {
              label:'保养',
              value:2,
            },
            {
              label:'其他',
              value:3
            }
          ]
        },
      ]
    },
    {
      name:'业务结算',
      params:['业务结算'],
      type:'',
      list:[
        {
          key:'业务单号',
          value:'',
          type:'default',
          prop:'orderCode',
        },
        {
          key:'会员名称',
          value:'',
          type:'default',
          prop:'realName',
        },
        {
          key:'会员电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'车牌号',
          value:'',
          type:'default',
          prop:'plateNum',
        },
        {
          key:'开始时间',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'结束时间',
          value:'',
          type:'date',
          prop:'endDate',
        },
        {
          key:'回复状态',
          value:'',
          type:'select',
          prop:'orderStatus',
          list:[
            {
              label:'已结算',
              value:1,
            },
            {
              label:'未结算',
              value:0,
            }
          ],
        },
      ]
    },
    {
      name:'业务出库',
      params:['业务出库'],
      type:'',
      list:[
        {
          key:'商品出库单号',
          value:'',
          type:'default',
          prop:'outRepositoryCode'
        },
        {
          key:'开始时间',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'结束时间',
          value:'',
          type:'date',
          prop:'endDate',
        }
      ]
    },
    {
      name:'业务退货',
      params:['业务退货'],
      type:'',
      list:[
        {
          key:'商品退货单号',
          value:'',
          type:'default',
          prop:'backCode',
        },
        {
          key:'开始时间',
          value:'',
          type:'date',
          prop:'startDate',
        },
        {
          key:'结束时间',
          value:'',
          type:'date',
          prop:'endDate',
        }
      ]
    },
    {
      name:'套餐管理',
      params:['套餐管理'],
      type:'',
      list:[
        {
          key:'套餐名称',
          value:'',
          type:'default',
          prop:'packageName'
        },
        {
          key:'套餐状态',
          value:'',
          type:'select',
          prop:'packageStatus',
          list:[
            {
              label:'已启用',
              value:1
            },
            {
              label:'已停用',
              value:0
            }
          ]
        }
      ]
    },
    {
      name:'套餐销售',
      params:['套餐销售'],
      type:'',
      list:[
        {
          key:'销售单号',
          value:'',
          type:'default',
        },
        {
          key:'销售名称',
          value:'',
          type:'default',
        },
        {
          key:'会员名称',
          value:'',
          type:'default',
        },
        {
          key:'会员电话',
          value:'',
          type:'default',
        },
        {
          key:'车牌号',
          value:'',
          type:'default',
        },
        {
          key:'销售人员',
          value:'',
          type:'default',
        },
        {
          key:'销售开始时间',
          value:'',
          type:'date',
        },
        {
          key:'销售结束时间',
          value:'',
          type:'date',
        },
      ]
    },
    {
      name:'会员套餐记录',
      params:['会员套餐记录'],
      type:'',
      list:[
        {
          key:'套餐名称',
          value:'',
          type:'default',
          prop:'name',
        },
        {
          key:'会员名称',
          value:'',
          type:'default',
          prop:'userName',
        },
        {
          key:'会员电话',
          value:'',
          type:'default',
          prop:'phone',
        },
        {
          key:'车牌号',
          value:'',
          type:'default',
          prop:'plateNum',
        },
        {
          key:'是否停用',
          value:'',
          type:'select',
          prop:'state',
          list:[
            {
              label:'已启用',
              value:1
            },
            {
              label:'已停用',
              value:0
            }
          ],
        },
      ]
    },
    {
      name:'采购订单',
      params:['采购订单','采购入库','采购退货'],
      type:'',
      list:[
        {
          key:'采购订单号',
          value:'',
          type:'default',
          prop:'purchaseCode',
        },
        {
          key:'开始时间',
          value:'',
          type:'date',
          prop:'startTime',
        },
        {
          key:'结束时间',
          value:'',
          type:'date',
          prop:'endTime',
        }
      ]
    },
    {
      name:'财务管理',
      params:['付款管理','挂账还款'],
      list:[
        {
          key:'订单号',
          type:'default',
          prop:'payCode',
        },
        {
          key:'开始时间',
          type:'date',
          prop:'startDate'
        },
        {
          key:'结束时间',
          type:'date',
          prop:'endDate',
        }
      ],
    },
    {
      name:'财务管理',
      params:['调拨发起'],
      list:[
        {
          key:'订单号',
          type:'default',
          prop:'outputCode',
        },
        {
          key:'开始日期',
          type:'date',
          prop:'startTime'
        },
        {
          key:'结束日期',
          type:'date',
          prop:'endTime',
        }
      ],
    },
    {
      name:'财务管理',
      params:['日常盘点'],
      list:[
        {
          key:'盘点单号',
          type:'default',
          prop:'checkNo',
        },
        {
          key:'开始日期',
          type:'date',
          prop:'startTime'
        },
        {
          key:'结束日期',
          type:'date',
          prop:'endTime',
        }
      ],
    },
    {
      name:'财务管理',
      params:['调拨接收'],
      list:[
        {
          key:'订单号',
          type:'default',
          prop:'inputCode',
        },
        {
          key:'开始日期',
          type:'date',
          prop:'startTime'
        },
        {
          key:'结束日期',
          type:'date',
          prop:'endTime',
        }
      ],
    },
    {
      name:'财务管理',
      params:['日常盘点'],
      list:[
        {
          key:'订单号',
          type:'default',
          prop:'checkNo',
        },
        {
          key:'开始时间',
          type:'date',
          prop:'startDate'
        },
        {
          key:'结束时间',
          type:'date',
          prop:'endDate',
        }
      ],
    },
    {
      name:'供应商设置',
      params:['供应商设置'],
      list:[
        {
          key:'供应商名称',
          type:'default',
          prop:'supplierName'
        },
        {
          key:'联系人姓名',
          type:'default',
          prop:'contactName'
        },
        {
          key:'联系人电话',
          type:'default',
          prop:'contactPhone'
        }
      ],
    },
    {
      name:'仓库设置',
      params:['仓库设置'],
      list:[
        {
          key:'仓库名称',
          type:'default',
          prop:'repositoryName',
        },
        {
          key:'联系电话',
          type:'default',
          prop:'contactPhone',
        },
        {
          key:'仓库管理员',
          type:'default',
          prop:'contactName',
        },
        {
          key:'地址',
          type:'default',
          prop:'address',
        },
      ],
    },
    {
      name:'商品分类设置',
      params:['商品分类设置'],
      list:[
        {
          key:'商品类型',
          type:'default',
          prop:'goodsClassificationName'
        }
      ]
    },
    {
      name:'商品设置',
      params:['商品设置'],
      list:[
        {
          key:'商品类型',
          type:'default',
          prop:'classificationId',
        },
        {
          key:'商品名称',
          type:'default',
          prop:'goodsName'
        },
        {
          key:'是否展示',
          type:'select',
          prop:'isShowShop',
          list:[
            {
              label:'是',
              value:1
            },
            {
              label:'否',
              value:0
            }
          ]
        },
      ]
    },
    {
      name:'项目分类设置',
      params:['项目分类设置'],
      list:[
        {
          key:'项目类型',
          type:'default',
          prop:'projectName'
        }
      ]
    },
    {
      name:'项目设置',
      params:['项目设置'],
      list:[
        {
          key:'项目类型',
          type:'default',
          prop:'projectTypeId',
        },
        {
          key:'项目名称',
          type:'default',
          prop:'projectName'
        }
      ]
    },
    {
      name:'物流公司配置',
      params:['物流公司配置'],
      list:[
        {
          key:'物流公司名称',
          type:'default',
          prop:'logisticsName',
        },
        {
          key:'联系电话',
          type:'default',
          prop:'contactPhone',
        },
        {
          key:'仓库管理员',
          type:'default',
          prop:'contactName',
        },
        {
          key:'地址',
          type:'default',
          prop:'address',
        }
      ]
    },
    {
      name:'支付方式配置',
      params:['支付方式配置'],
      list:[
        {
          key:'支付方式名称',
          type:'default',
        }
      ]
    },
    {
      name:'库存报表',
      params:['库存报表'],
      type:'',
      list:[
        {
          key:'商品类名',
          value:'',
          type:'default',
          prop:'goodsClassificationName',
        },
        {
          key:'商品名称',
          value:'',
          type:'default',
          prop:'goodsName',
        },
        {
          key:'仓库名称',
          value:'',
          type:'default',
          prop:'repositoryName',
        }
      ]
    },
    {
      name:'出入库明细表',
      params:['出入库明细表'],
      type:'',
      list:[
        {
          key:'商品类名',
          value:'',
          type:'default',
          prop:'goodsName',
        },
        {
          key:'起点时间',
          value:'',
          type:'date',
          prop:'startTime',
        },
        {
          key:'终点时间',
          value:'',
          type:'date',
          prop:'endTime',
        }
      ]
    },
    {
      name:'盘点明细表',
      params:['盘点明细表'],
      type:'',
      list:[
        {
          key:'商品名称',
          value:'',
          type:'default',
          prop:'goodName',
        },
        {
          key:'起点时间',
          value:'',
          type:'date',
          prop:'startTime',
        },
        {
          key:'终点时间',
          value:'',
          type:'date',
          prop:'endTime',
        }
      ]
    },
    {
      name:'采购明细表',
      params:['采购明细表'],
      type:'',
      list:[
        {
          key:'商品名称',
          value:'',
          type:'default',
          prop:'goodsName',
        },
        {
          key:'起点时间',
          value:'',
          type:'date',
          prop:'startTime',
        },
        {
          key:'终点时间',
          value:'',
          type:'date',
          prop:'endTime',
        }
      ]
    },
    {
      name:'日报月报',
      params:['日报月报'],
      type:'',
      list:[
        {
          key:'商品名称',
          value:'',
          type:'default',
          prop:'goodName',
        },
        {
          key:'仓库名称',
          value:'',
          type:'default',
          prop:'repositoryName',
        },
        {
          key:'起点时间',
          value:'',
          type:'date',
          prop:'startTime',
        },
        {
          key:'终点时间',
          value:'',
          type:'date',
          prop:'endTime',
        }
      ]
    },
    {
      name:'销售统计表',
      params:['销售统计表'],
      type:'',
      list:[
        {
          key:'客户名称',
          value:'',
          type:'default',
          prop:'userName'
        },
        {
          key:'业务单号',
          value:'',
          type:'default',
          prop:'businessNo',
        },
        {
          key:'起点时间',
          value:'',
          type:'date',
          prop:'startTime',
        },
        {
          key:'终点时间',
          value:'',
          type:'date',
          prop:'endTime',
        }
      ]
    },
    {
      name:'商品销售统计',
      params:['商品销售统计'],
      type:'',
      list:[
        {
          key:'统计类型',
          type:'select',
          list:[
            {
              label:'按商品',
              value:1
            },
            {
              label:'按客户',
              value:2
            },
            {
              label:'按销售员',
              value:3
            },
            {
              label: '按施工员',
              value:4
            }
          ]
        },
        {
          key:'商品编号',
          value:'',
          type:'default',
          prop:'',
        },
        {
          key:'商品名称',
          value:'',
          type:'default',
          prop:'',
        },
        {
          key:'起点时间',
          value:'',
          type:'date',
          prop:'',
        },
        {
          key:'终点时间',
          value:'',
          type:'date',
          prop:'',
        }
      ]
    },
    {
      name:'项目销售统计',
      params:['项目销售统计'],
      type:'',
      list:[
        {
          key:'项目名称',
          type:'default',
          prop:'',
        },
        {
          key:'起点时间',
          type:'date',
          prop:'',
        },
        {
          key:'终点时间',
          type:'date',
          prop:'',
        }
      ]
    },
    {
      name:'挂账单据明细表',
      params:['挂账单据明细表','挂账还款明细表'],
      type:'',
      list:[
        {
          key:'车牌号',
          type:'default',
          prop:'plateNum',
        },
        {
          key:'起点时间',
          type:'date',
          prop:'startendDate',
        },
        {
          key:'终点时间',
          type:'date',
          prop:'endendDate',
        }
      ]
    },
    {
      name:'收付款统计',
      params:['收款统计','付款统计','营业额统计表'],
      type:'',
      list:[
        {
          key:'起点时间',
          type:'date',
          prop:'startcreateDate',
        },
        {
          key:'终点时间',
          type:'date',
          prop:'endCreateDate',
        }
      ]
    },
    {
      name:'用户统计',
      params:['用户统计'],
      type:'',
      list:[
        {
          key:'报表类型',
          type:'select',
          prop:'',
          list:[
            {
              label:'日报',
              value:1
            },
            {
              label:'月报',
              value:2
            },
            {
              label:'年报',
              value:3
            }
          ],
        },
        {
          key:'统计类型',
          type:'select',
          prop:'',
          list:[
            {
              label:'全部',
              value:1,
            },
            {
              label:'车主新增',
              value:2,
            },
            {
              label:'车主流失',
              value:3,
            }
          ]
        },
        {
          key:'开始时间',
          type:'date',
          prop:'',
        },
        {
          key:'结束时间',
          type:'date',
          prop:''
        },
        {
          key:'统计方式',
          type:'select',
          prop:'showType',
          list:[
            {
              label:'柱状图',
              value:1,
            },
            {
              label:'折线图',
              value:2,
            },
            {
              label:'表格',
              value:3,
            }
          ]
        }
      ]
    },
    {
      name:'车辆统计',
      params:['车辆统计'],
      type:'',
      list:[
        {
          key:'统计类型',
          type:'select',
          prop:'',
          list:[
            {
              label:'按类型',
              value:1
            },
            {
              label:'按车品牌',
              value:2
            }
          ],
        },
        {
          key:'开始时间',
          type:'date',
          prop:'',
        },
        {
          key:'结束时间',
          type:'date',
          prop:''
        },
      ]
    },
    {
      name:'业务统计',
      params:['业务统计'],
      type:'',
      list:[
        {
          key:'统计类型',
          type:'select',
          prop:'',
          list:[
            {
              label:'日报',
              value:1
            },
            {
              label:'月报',
              value:2
            },
            {
              label:'年报',
              value:3
            }
          ],
        },
        {
          key:'报表类型',
          type:'select',
          prop:'',
          list:[
            {
              label:'预约服务',
              value:1
            },
            {
              label:'续保询价',
              value:2
            },
            {
              label:'违章代办',
              value:3
            },
            {
              label:'救援服务',
              value:4
            }
          ],
        },
        {
          key:'开始时间',
          type:'date',
          prop:'',
        },
        {
          key:'结束时间',
          type:'date',
          prop:''
        },
        {
          key:'统计方式',
          type:'select',
          prop:'',
          list:[
            {
              label:'柱状图',
              value:1
            },
            {
              label:'折线图',
              value:2
            },
            {
              label:'表格',
              value:3
            }
          ]
        }
      ]
    },
    {
      name:'活动统计',
      params:['活动统计'],
      type:'',
      list:[
        {
          key:'统计类型',
          type:'select',
          prop:'',
          list:[
            {
              label:'普通活动',
              value:1
            },
            {
              label:'活动抽奖',
              value:2
            },
            {
              label:'推荐有礼',
              value:3
            },
            {
              label:'摇一摇',
              value:4
            }
          ],
        },
        {
          key:'开始时间',
          type:'date',
          prop:'',
        },
        {
          key:'结束时间',
          type:'date',
          prop:''
        }
      ]
    },
    {
      name:'会员统计',
      params:['会员统计','提成日报'],
      type:'',
      list:[
        {
          key:'开始时间',
          type:'date',
          prop:'',
        },
        {
          key:'结束时间',
          type:'date',
          prop:''
        }
      ]
    },
    {
      name:'明细查询',
      params:['明细查询'],
      type:'',
      list:[
        {
          key:'姓名',
          type:'default',
          prop:'name',
        },
        {
          key:'联系电话',
          type:'default',
          prop:'phone',
        },
        {
          key:'开始日期',
          type:'date',
          prop:'joinTimeStr',
        },
        {
          key:'结束日期',
          type:'date',
          prop:'joinTimeEnd'
        }
      ]
    },
  ],
  btnList:[
    {
      name:'门店管理',
      type:'',
      params:['门店管理'],
      list:[
        {
          text:'查询',
          type:'default',
          size:'small',
          click:handleSearchList,
        },
        {
          text:'重置',
          type:'default',
          size:'small',
          click:clearSearchForm,
        },
        {
          text:'当前机构',
          type:'default',
          size:'small',
          click:''
        }
      ]
    },
    {
      name:'查询重置类别',
      params:['员工列表','快捷回复设置','保险公司','汽车精品管理','精品订单管理','配件大类管理','会员列表','车辆管理', '操作日志' ,'积分管理','充值明细','消费明细','奖品卡券管理','用户卡券管理','用户卡券发放','用户奖励','员工奖励','用户提现记录','查看领取明细','用户佣金提现','普通活动','精准获客','活动抽奖','推荐有礼','预约管理','意见反馈','业务开单','业务结算','套餐销售','会员套餐记录','库存报表', '盘点明细表', '出入库明细表', '日报月报','销售统计表','商品销售统计','项目销售统计','采购明细表','挂账单据明细表','挂账还款明细表','收款统计','付款统计'],
      type:'',
      list:[
        {
          text:'查询',
          type:'default',
          size:'small',
          click:handleSearchList,
        },
        {
          text:'重置',
          type:'default',
          size:'small',
          click:clearSearchForm,
        }
      ]
    },
    {
      name: '查询重置类别',
      desc:'重置之后不再刷新',
      params:['会员充值'],
      list:[
        {
          text: '查询',
          type: 'default',
          size: 'small',
          click: handleSearchList
        },
        {
          text:'重置',
          type:'default',
          size:'small',
          click: handleClearSearch
        }
      ]
    }
  ]
}

const actions = {}

const mutations = {}

const getters = {
  getSearchListByPrams : (state, rootGetters, rootState) => parmas => {
    let arr =  state.types.filter(item => item.params && item.params.includes(parmas.name))
    arr.map(item => {
      item.list.map(sub => {
        if(sub.key === '请选择精品大类' && sub.type === 'select'){
          sub.list = rootGetters.formatCarTypeList
        }else if(sub.key === '卡券类型' && sub.type === 'select'){
          sub.list = rootGetters.formatCouponList
        }else if((sub.key === '会员等级') && (item.name === '用户卡券发放')){
          sub.list = rootState.level_List
        }else if((sub.key === '会员等级') && (item.name !== '用户卡券发放')){
          sub.list = rootGetters.formatMemberList
        }else if(sub.key === '业务类型'){
          sub.list = rootState.Member.tempArr1
        }else if(sub.key === '充值方式'){
          sub.list = rootState.Member.tempArr1
        }else if(sub.key === '活动卡券' && item.name !== '用户奖励'){
          sub.list = rootGetters.formatCouponActivityList
        }else if(sub.key === '保养顾问'){
          sub.list = rootState.upKeepList
        }else if(sub.key === '保险顾问'){
          sub.list = rootState.inSuranceList
        }else if(sub.key === '续保顾问'){
          sub.list = rootState.renewList
        }else if(sub.key === '销售顾问'){
          sub.list = rootState.sellList
        }else if(sub.key === '卡券来源'){
          sub.list = rootGetters.formatCouponSrouce  
        }else if((sub.key === '活动卡券') && (item.name === '用户奖励')){
          sub.list = rootGetters.formatPariseList[0]
        }else if(sub.key === '使用角色类型'){
          sub.list = rootGetters.formatRoleList
        }else if(sub.key === '文章类别'){
          sub.list = rootState.articleType
        }else if(sub.key === '活动栏目'){
          sub.list = rootState.activitiesList
        }
        return {...sub}
      })
      return {...item}
    })
    return arr[0] ? arr[0].list : []
  },
  getSearchBtnsByParams :state => params => {
    const arr = state.btnList.filter(item => item.params && item.params.includes(params.name))
    return arr[0] ? arr[0].list : []
  }
}

export default {
  state , actions , mutations , getters
}