const state = {
  search:{

  },
  types:[
    {
      name:'门店管理',
      params:['门店管理'],
      type:'',
      list:[
        {
          key:'门店名称',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'类型',
          type:'select',
          prop:'type',
          value:'',
        },
        {
          key:'服务开始日期',
          type:'date',
          prop:'start',
          value:'',
        },
        {
          key:'服务结束日期',
          type:'date',
          prop:'end',
          value:'',
        },
        {
          key:'状态',
          type:'select',
          prop:'state',
          value:'',
        }
      ]
    },
    {
      name:'staff',
      type:'',
      params:['员工管理','员工列表'],
      list:[
        {
          key:'姓名',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'phone',
          value:'',
        },
        {
          key:'性别',
          type:'input',
          prop:'gender',
          value:'',
        },
        {
          key:'微信昵称',
          type:'input',
          prop:'nickName',
          value:'',
        }
      ]
    },
    {
      name:'staffAdd',
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          prop:'',
          type:'input',
        },
        {
          key:'联系电话',
          value:'',
          prop:'',
          type:'input',
        },
        {
          key:'性别',
          value:'',
          prop:'',
          type:'select',
        }
      ]
    },
    {
      name:'保险公司',
      type:'',
      params:['保险公司'],
      list:[
        {
          key:'保险公司名称',
          type:'input',
          value:'',
          prop:'',
        }
      ]
    },
    {
      name:'快捷回复设置',
      type:'',
      params:['快捷回复设置'],
      list:[
        {
          key:'使用角色类型',
          type:'select',
          value:'',
          prop:'',
        }
      ]
    },
    {
      name:'汽车精品管理',
      type:'',
      params:['汽车精品管理'],
      list:[
        {
          key:'配件名称',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'请选择精品大类',
          type:'select',
          prop:'type',
          value:'',
        },
        {
          key:'是否推荐',
          type:'select',
          prop:'start',
          value:'',
        },
        {
          key:'积分兑换',
          type:'select',
          prop:'end',
          value:'',
        },
        {
          key:'商品状态',
          type:'select',
          prop:'state',
          value:'',
        }
      ]
    },
    {
      name:'精品订单管理',
      params:['精品订单管理'],
      type:'',
      list:[
        {
          key:'订单编号',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'姓名',
          type:'input',
          prop:'type',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'start',
          value:'',
        },
        {
          key:'配件名称',
          type:'input',
          prop:'end',
          value:'',
        },
        {
          key:'状态',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'下单开始日期',
          type:'date',
          value:'',
          prop:'',
        },
        {
          key:'下单结束日期',
          type:'date',
          value:'',
          prop:'',
        },
        {
          key:'提货开始日期',
          type:'date',
          value:'',
          prop:'',
        },
        {
          key:'提货结束日期',
          type:'date',
          value:'',
          prop:'',
        }
      ]
    },
    {
      name:'配件大类管理',
      params:['配件大类管理'],
      type:'',
      list:[
        {
          key:'精品大类名称',
          type:'input',
          value:'',
          prop:'',
        }
      ]
    },
    {
      name:'会员列表',
      type:'',
      params:['会员列表'],
      list:[
        {
          key:'姓名',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'联系电话',
          type:'select',
          prop:'type',
          value:'',
        },
        {
          key:'会员等级',
          type:'select',
          prop:'start',
          value:'',
        },
        {
          key:'性别',
          type:'select',
          prop:'end',
          value:'',
        },
        {
          key:'顾问类型',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'状态',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'推荐人',
          type:'input',
          prop:'state',
          value:'',
        },
        {
          key:'车辆',
          type:'input',
          prop:'state',
          value:'',
        },
        {
          key:'车型',
          type:'input',
          prop:'state',
          value:'',
        },
        {
          key:'关注开始日期',
          type:'date',
          prop:'state',
          value:'',
        },
        {
          key:'关注结束日期',
          type:'date',
          prop:'state',
          value:'',
        },
        {
          key:'积分区间(最小值)',
          type:'input',
          prop:'state',
          value:'',
        },
        {
          key:'积分区间(最大值)',
          type:'select',
          prop:'state',
          value:'',
        },
      ]
    }, 
    {
      name:'车辆管理',
      type:'',
      params:['车辆管理'],
      list:[
        {
          key:'姓名',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'联系电话',
          type:'select',
          prop:'type',
          value:'',
        },
        {
          key:'上次开始保养日期',
          type:'date',
          prop:'start',
          value:'',
        },
        {
          key:'上次保养结束日期',
          type:'date',
          prop:'end',
          value:'',
        },
        {
          key:'保养到期',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'保险购买开始日期',
          type:'date',
          prop:'state',
          value:'',
        },
        {
          key:'保险购买结束日期',
          type:'date',
          prop:'state',
          value:'',
        },
        {
          key:'保险到期',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'车型',
          type:'input',
          prop:'state',
          value:'',
        },
        {
          key:'车牌号',
          type:'input',
          prop:'state',
          value:'',
        }
      ]
    },
    {
      name:'积分管理',
      params:['积分管理'],
      type:'',
      list:[
        {
          key:'会员姓名',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'联系电话',
          type:'select',
          prop:'type',
          value:'',
        },
        {
          key:'微信昵称',
          type:'input',
          prop:'type',
          value:'',
        },
        {
          key:'积分发生开始日期',
          type:'date',
          prop:'start',
          value:'',
        },
        {
          key:'积分发生结束日期',
          type:'date',
          prop:'end',
          value:'',
        },
        {
          key:'会员等级',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'积分改变类型',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'业务类型',
          type:'select',
          prop:'state',
          value:'',
        },
      ]
    },  
    {
      name:'充值明细',
      params:['充值明细'],
      type:'',
      list:[
        {
          key:'订单号',
          type:'input',
          prop:'name',
          value:'',
        },
        {
          key:'会员姓名',
          type:'select',
          prop:'type',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'type',
          value:'',
        },
        {
          key:'操作人',
          type:'input',
          prop:'start',
          value:'',
        },
        {
          key:'充值方式',
          type:'select',
          prop:'end',
          value:'',
        },
        {
          key:'开始日期',
          type:'date',
          prop:'state',
          value:'',
        },
        {
          key:'结束日期',
          type:'date',
          prop:'state',
          value:'',
        },
      ]
    }, 
    {
      name:'消费明细',
      params:['消费明细'],
      type:'',
      list:[
        {
          key:'会员姓名',
          type:'select',
          prop:'type',
          value:'',
        },
        {
          key:'联系电话',
          type:'input',
          prop:'type',
          value:'',
        },
        {
          key:'车牌号',
          type:'input',
          prop:'start',
          value:'',
        },
        {
          key:'选择消费项目',
          type:'select',
          prop:'end',
          value:'',
        },
        {
          key:'会员卡扣除状态',
          type:'select',
          prop:'state',
          value:'',
        },
        {
          key:'开始日期',
          type:'date',
          prop:'',
          value:''
        },
        {
          key:'结束日期',
          type:'date',
          prop:'state',
          value:'',
        },
      ]
    },
    {
      name:'奖品卡券管理',
      params:['奖品卡券管理'],
      type:'',
      list:[
        {
          key:'卡券名称',
          type:'input',
          prop:'',
          value:'',
        },
        {
          key:'卡券类型',
          type:'select',
          prop:'',
          value:'',
        },
        {
          key:'有效日期',
          type:'select',
          prop:'',
          value:'',
        }
      ]
    },
    {
      name:'抽奖模板设置',
      params:['抽奖模板设置'],
      type:'',
      list:[
        {
          key:'模板名称',
          type:'input',
          prop:'',
          default:'',
        }
      ]
    },
    {
      name:'用户卡券管理',
      params:['用户卡券管理'],
      type:'',
      list:[
        {
          key:'姓名',
          prop:'',
          type:'input',
          value:''
        },
        {
          key:'联系电话',
          prop:'',
          type:'input',
          value:''
        },
        {
          key:'卡券名称',
          prop:'',
          type:'input',
          value:''
        },
        {
          key:'卡券编号',
          prop:'',
          type:'input',
          value:''
        },
        {
          key:'卡券类型',
          prop:'',
          type:'select',
          value:''
        },
        {
          key:'获取开始日期',
          prop:'',
          type:'date',
          value:''
        },
        {
          key:'获取结束日期',
          prop:'',
          type:'date',
          value:''
        },
        {
          key:'状态',
          prop:'',
          type:'select',
          value:''
        },
        {
          key:'来源',
          prop:'',
          type:'select',
          value:''
        },
      ]
    },
    {
      name:'用户卡券发放',
      params:['用户卡券发放'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'车型',
          value:'',
          type:'default',
        },
        {
          key:'车牌',
          value:'',
          type:'default',
        },
        {
          key:'性别',
          value:'',
          type:'select',
        },
        {
          key:'会员级别',
          value:'',
          type:'select',
        },
        {
          key:'销售顾问',
          value:'',
          type:'select',
        },
        {
          key:'保养顾问',
          value:'',
          type:'select',
        },
        {
          key:'保险顾问',
          value:'',
          type:'select',
        },
        {
          key:'续保顾问',
          value:'',
          type:'select',
        },
        {
          key:'个人信息',
          value:'',
          type:'select',
        },
        {
          key:'车辆信息',
          value:'',
          type:'select',
        },
      ]
    },
    {
      name:'用户提现',
      params:['用户提现记录'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'车牌号',
          value:'',
          type:'default',
        },
        {
          key:'提现开始日期',
          value:'',
          type:'date',
        },
        {
          key:'提现结束日期',
          value:'',
          type:'date'
        }
      ],
    },
    {
      name:'用户奖励',
      params:['用户奖励'],
      type:'',
      list:[
        {
          key:'用户姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'奖励类型',
          value:'',
          type:'select',
        },
        {
          key:'活动卡券',
          value:'',
          type:'select',
        },
        {
          key:'消费最小金额',
          value:'',
          type:'input',
        },
        {
          key:'消费最大金额',
          value:'',
          type:'input',
        },
        {
          key:'返利开始日期',
          value:'',
          type:'date',
        },
        {
          key:'返利结束日期',
          value:'',
          type:'date',
        },
        {
          key:'单词分享用户数',
          value:'',
          type:'select',
        },
        {
          key:'奖励金额',
          value:'',
          type:'select',
        }
      ]
    },
    {
      name:'员工奖励',
      params:['员工奖励'],
      type:'',
      list:[
        {
          key:'员工姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'消费最小金额',
          value:'',
          type:'input',
        },
        {
          key:'消费最大金额',
          value:'',
          type:'input',
        },
        {
          key:'奖励开始日期',
          value:'',
          type:'date',
        },
        {
          key:'奖励结束日期',
          value:'',
          type:'date',
        },
        {
          key:'活动卡券',
          value:'',
          type:'select',
        },
        {
          key:'发放状态',
          value:'',
          type:'select',
        },
        {
          key:'奖励类型',
          value:'',
          type:'select',
        }
      ]
    },
    {
      name:'普通活动',
      params:['普通活动','活动抽奖'],
      type:'',
      list:[
        {
          key:'活动标题',
          value:'',
          type:'default',
        },
        {
          key:'活动开始日期',
          value:'',
          type:'date',
        },
        {
          key:'活动结束日期',
          value:'',
          type:'date',
        },
        {
          key:'发布开始日期',
          value:'',
          type:'date',
        },
        {
          key:'发布结束日期',
          value:'',
          type:'date',
        },
        {
          key:'活动栏目',
          value:'',
          type:'select',
        },
        {
          key:'全部活动',
          value:'',
          type:'select',
        },
      ],
    },
    {
      name:'推荐有礼',
      params:['推荐有礼'],
      type:'',
      list:[
        {
          key:'推荐人手机号',
          value:'',
          type:'default',
        },
        {
          key:'被推荐人手机号',
          value:'',
          type:'default',
        },
        {
          key:'推荐类型',
          value:'',
          type:'select',
        },
        {
          key:'推荐状态',
          value:'',
          type:'select',
        },
        {
          key:'推荐开始日期',
          value:'',
          type:'date',
        },
        {
          key:'推荐结束日期',
          value:'',
          type:'date',
        },
      ],
    },
    {
      name:'摇一摇活动',
      params:['摇一摇活动'],
      type:'',
      list:[
        {
          key:'场次名称',
          value:'',
          type:'default',
        },
        {
          key:'发布开始日期',
          value:'',
          type:'date',
        },
        {
          key:'发布结束日期',
          value:'',
          type:'date',
        },
        {
          key:'活动状态',
          value:'',
          type:'select',
        }
      ],
    },
    {
      name:'预约管理',
      params:['预约管理'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'预约类型',
          value:'',
          type:'select',
        },
        {
          key:'预约状态',
          value:'',
          type:'select',
        },
        {
          key:'预约开始时间',
          value:'',
          type:'date',
        },
        {
          key:'预约结束时间',
          value:'',
          type:'date',
        },
      ]
    },
    {
      name:'保险服务',
      params:['保险服务'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'状态',
          value:'',
          type:'select',
        },
      ]
    },
    {
      name:'检修记录',
      params:['检修记录'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'车牌',
          value:'',
          type:'default',
        },
        {
          key:'检测开始时间',
          value:'',
          type:'date',
        },
        {
          key:'检测结束时间',
          type:'date',
          value:'',
        }
      ]
    },
    {
      name:'救援服务',
      params:['救援服务'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
      ]
    },
    {
      name:'养车知识',
      params:['养车知识'],
      type:'',
      list:[
        {
          key:'文章标题',
          value:'',
          type:'default',
        },
        {
          key:'文章类别',
          value:'',
          type:'select'
        }
      ]
    },
    {
      name:'意见反馈',
      params:['意见反馈'],
      type:'',
      list:[
        {
          key:'姓名',
          value:'',
          type:'default',
        },
        {
          key:'联系电话',
          value:'',
          type:'default',
        },
        {
          key:'反馈开始时间',
          value:'',
          type:'date'
        },
        {
          key:'反馈结束时间',
          value:'',
          type:'date'
        },
        {
          key:'回复状态',
          value:'',
          type:'select'
        },
        {
          key:'反馈类型',
          value:'',
          type:'select'
        },
      ]
    }
  ],
  btnList:[
    {
      name:'门店管理',
      type:'',
      params:['门店管理'],
      list:[
        {
          text:'查询',
          type:'default',
          size:'small',
          click:'',
        },
        {
          text:'重置',
          type:'default',
          size:'small',
          click:'',
        },
        {
          text:'当前机构',
          type:'default',
          size:'small',
          click:''
        }
      ]
    },
    {
      name:'查询重置类别',
      params:['员工列表','保险公司','快捷回复设置','汽车精品管理','精品订单管理','配件大类管理','会员列表','车辆管理','积分管理','充值明细','消费明细','奖品卡券管理','用户卡券管理','用户卡券发放','用户奖励','员工奖励','用户提现记录','普通活动','活动抽奖','推荐有礼','预约管理','意见反馈'],
      type:'',
      list:[
        {
          text:'查询',
          type:'default',
          size:'small',
          click:'',
        },
        {
          text:'重置',
          type:'default',
          size:'small',
          click:'',
        }
      ]
    },
  ]
}

const actions = {}

const mutations = {}

const getters = {
  getSearchListByPrams : state => parmas => {
    const arr =  state.types.filter(item => item.params && item.params.includes(parmas.name))
    return arr[0] ? arr[0].list : []
    // return state.types.find(item => item.params && item.params.includes(parmas.name) ? item : []).list
  },
  getSearchBtnsByParams :state => params => {
    const arr = state.btnList.filter(item => item.params && item.params.includes(params.name))
    return arr[0] ? arr[0].list : []
    // return state.btnList.find(item => item.params && item.params.includes(params.name) ? item : []).list
  }
}

export default {
  state , actions , mutations , getters
}